### PR TITLE
Update lvlgen.js

### PR DESCRIPTION
**Pull request by W1LKC0**
FRENCH traduction of files / Traduction en francais du fichier.

### CODE REVIEW

**Comment by clairekardas** [comment]
#60 ... Dont spam pls.

"I dont think that much persons in France using agar lvlgen.
And i hope everyone there can speak english too... We cant add every language, but im not a mod^^"

**Comment by W1LKC0** [comment]
TWO different files... its not an spam. Please read.

**Comment by clairekardas** [comment]
Yeah, but you can edit 2 files in one request :)

**Comment by W1LKC0** [comment]
ohhh.... i have difficult with git website haha ... sorry for double post ;)

**Comment by clairekardas** [comment]
No problem :) but can you told me why we need englisch and french? :D

**Comment by W1LKC0** [comment]
I don't know how to make change in same pull request :O

**Comment by makandz** [comment]
We should make a separate branches for different languages :)

**Comment by clairekardas** [comment]
I make German!!11eleven

**Comment by Salvationdk** [comment]
if translation is needed it should be made in a lang file instead of total translation of each files...

**Comment by makandz** [comment]
^^^^^^^^^

**Comment by makandz** [comment]
I'm going to make a lang file for this ;)

**Pull request closed without merging**
