### PR TITLE
logging option + version

### PR DESCRIPTION
**Pull request by Salvationdk**

### CODE REVIEW

**Comment by Salvationdk** [comment]
there it is.. logging option for program start, token error, token accepted, score above 500, and restart notice... logged in log.txt file with date time

**Comment by Salvationdk** [comment]
the logging of point is still a bit buggy, it keeps writing the score linewhen you hit 500

> Mon Mar 28 2016 21:34:43 GMT+0200 (Rom, sommertid) | **\* HIGHEST SCORE ABOVE 500 **\* 
> Mon Mar 28 2016 21:34:44 GMT+0200 (Rom, sommertid) | **\* HIGHEST SCORE ABOVE 500 **\* 
> Mon Mar 28 2016 21:34:45 GMT+0200 (Rom, sommertid) | **\* HIGHEST SCORE ABOVE 500 **\* 
> Mon Mar 28 2016 21:34:46 GMT+0200 (Rom, sommertid) | **\* HIGHEST SCORE ABOVE 500 **\* 

will be fixed unless someone else fixes this in a pull :)

**Comment by makandz** [comment]
I can't send out a pull because I'm behind :-1: Just gotta wait for Crazy to accept and I can start my work on it :3

**Comment by Salvationdk** [comment]
you can merge with mine and continue editing and adding to this PR :)

**Comment by makandz** [comment]
I just figured it out, I accepted your merge, now all I have to do is edit mine and you can merge mine with yours so it get's added :+1:

**Comment by Salvationdk** [comment]
;-)

Den 28/03/2016 21.57 skrev "Makan Dey" notifications@github.com:

**Comment by makandz** [comment]
@Salvationdk Made a PR. :+1:

**Comment by Cr4xy** [comment]
Amazing work guys!! :+1:

**Pull request merged**
