### PR TITLE
Update config.js

### PR DESCRIPTION
**Pull request by W1LKC0**
Traduction FRANCAISE des instructions de configuration / FRENCH TRADUCTION of instruction for configure.

### CODE REVIEW

**Comment by clairekardas** [comment]
I dont think that much persons in France using agar lvlgen.
And i hope everyone there can speak english too... We cant add every language, but im not a mod^^

**Comment by makandz** [comment]
^^

**Comment by 007Unknown** [comment]
@W1LKC0 @MastaCoder If you guys need I can do the same to Spanish & Portuguese, there are some people from that languages that ask me about agar-lvlgen
~srry for bad english

**Comment by makandz** [comment]
LANG FILE!!!

**Pull request closed without merging**
