### PR TITLE
Adding dev-tools submodule

### PR DESCRIPTION
**Pull request by moerderin**

### CODE REVIEW

**Comment by makandz** [comment]
Wait is this added to stream the game and record it?

**Comment by ncmp** [comment]
I guess so but do we really need that feature? Maybe it would be nice to watch how bot plays and analyze its performance based on recordings but I really dont know

**Comment by makandz** [comment]
@suxosuxo123 Yes but don't forget. We are running these bots on crappy mini servers which probably have 1 CPU. Some are even running on a rasberry pi, recording these will KILL the CPU.

**Comment by moerderin** [comment]
Well, I'm running it on my desktop. It's useful for streaming it because
then I can visually watch the ai performance

**Comment by makandz** [comment]
I (imo) think we should make a different branch for a more CPU intensive version of this bot and one that is good for multiple account running.

**Comment by moerderin** [comment]
I'm cool with that. I mean the piece is just a sub module that most people
won't use anyways. We can even shove it in one of those nested folders too
and nobody will be the wiser, lol.

**Comment by ncmp** [comment]
Yea I agree I use bot on my 4 core i7 cpu and 16 gb ram so I want a more cpu intensive bot if it improves performance

**Pull request closed without merging**
