### PR TITLE
Logging option

### PR DESCRIPTION
**Pull request by Salvationdk**
Logging option

### CODE REVIEW

**Comment by Salvationdk** [comment]
I merged MastaCoders into mine and added the option to write stats to a file, for review of the agar-lvlgen running

**Comment by makandz** [comment]
I like this :+1: I'm closing my PR now :3

**Comment by Salvationdk** [comment]
:)

**Comment by clairekardas** [comment]
Cant wait to see my lvlgen mass record lol... The most what i saw was 1800 :)

**Comment by Salvationdk** [comment]
im currently only logging above 500

when score = 500 it writes a log. nothing else yet

besides program restart time and token error etc

**Comment by makandz** [comment]
@Salvationdk Can you also update the version? I forgot to do that.

**Comment by makandz** [comment]
AND THE VERSION FILE :3

**Comment by makandz** [comment]
Close this :3

**Pull request closed without merging**
