### PR TITLE
Update the reset timer

### PR DESCRIPTION
**Pull request by makandz**
In this update, I merged the setTimeout in with the current seconds so it should use a _bit_ more CPU then before because it's basically calculating every seconds twice as much. However, you shouldn't see too much of a difference.

In this update I added the feature where the server will not reset unless if the bot average mass is less than 100, so no more worrying that your 500 mass bot will die because of a server reset and you getting no XP :3

I'll have the clean the code a crap ton to help release mb's of ram, but for now this is great!

### CODE REVIEW

**Comment by makandz** [comment]
I just read over the code again and looks pretty efficient now to me :+1:

**Comment by moerderin** [comment]
why are you updating the version in 2 places? why not just include the version file in lvlgen?

**Comment by makandz** [comment]
@moerderin When people download the file, it checked the version at the version file on Github.

**Comment by clairekardas** [comment]
Tested it out already, works pretty well :)

**Comment by Cr4xy** [comment]
Nice improvements! :)

**Comment by NoorAgario** [comment]
How can we use this @Cr4xy  @MastaCoder

**Comment by makandz** [comment]
@NoorAgario There is an option in the config.js to change the minutes for the restart.

**Comment by NoorAgario** [comment]
should I download the whole Agar-lvlgenerator again ? @MastaCoder

**Comment by makandz** [comment]
Yeah @NoorAgario

**Pull request merged**
